### PR TITLE
feat: Add basic auth support

### PR DESCRIPTION
**Pull request by cdvv7788**
Minor PR that adds support for basic auth and add a small example.

### CODE REVIEW

**Comment by markphelps** [comment]
Thanks for the PR @cdvv7788 ! 

Since Flipt Server doesnt natively support basic auth, is this for the case where you are running Flipt behind a reverse proxy such as nginx or caddy?

**Comment by cdvv7788** [comment]
Yep, running it behind nginx. May be a common enough case, and it is simple to support it :)

**Comment by markphelps** [comment]
@cdvv7788 what if instead we add the ability to set arbitrary headers? Adding support for manipulating headers in all clients seems more flexible / reasonable for us to maintain.

Especially since Flipt itself doesn't support basic auth, it might be a bit confusing to users of the SDKs if they see a `BasicAuthentication` method in the SDKs

**Comment by markphelps** [comment]
@cdvv7788 wdyt about changing this PR to allow setting the headers directly instead?

Then we can open up issues to do it in the other languages as well

**Pull request closed without merging**
